const {chromium}=require('playwright');
const {createApp}=require('../src/app');
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const out=path.resolve(__dirname,'../../test-results');fs.mkdirSync(out,{recursive:true});
(async()=>{
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'zc-browser-'));const app=createApp({dbPath:dir+'/business.sqlite',setupToken:'browser-test-code'});
await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
let browser;try{browser=await chromium.launch({headless:true});}catch(e){await new Promise(r=>app.server.close(r));fs.rmSync(dir,{recursive:true,force:true});throw e;}const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});
async function submit(label){await page.getByRole('button',{name:label,exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog').open);}
async function nav(name){await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();}
try{
await page.goto(base);await page.getByLabel('Setup code from the server window').fill('browser-test-code');await page.getByLabel('Your name').fill('Demo Owner');await page.getByLabel('Username',{exact:true}).fill('owner');await page.getByLabel('Password · at least 12 characters').fill('browser-password-123');await page.getByRole('button',{name:'Create workspace'}).click();await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();
await nav('Settings');await page.getByLabel('Business name').fill('Northline Supply');await page.getByLabel('Business address').fill('Bangkok, Thailand');await page.getByRole('button',{name:'Save business details'}).click();await page.getByText('Business details saved.',{exact:true}).waitFor();
await nav('Inventory');await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByLabel('SKU · unique identifier').fill('NB-001');await page.getByLabel('Product name',{exact:true}).fill('Everyday notebook');await page.getByLabel('Selling price',{exact:true}).fill('125');await page.getByLabel('Reference unit cost',{exact:true}).fill('60');await page.getByLabel('Opening stock').fill('35');await submit('Save product');
await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByLabel('SKU · unique identifier').fill('PN-002');await page.getByLabel('Product name',{exact:true}).fill('Studio pen set');await page.getByLabel('Selling price',{exact:true}).fill('240');await page.getByLabel('Reference unit cost',{exact:true}).fill('120');await page.getByLabel('Opening stock').fill('4');await submit('Save product');
await nav('Contacts');await page.getByRole('button',{name:'+ Add contact'}).click();await page.getByLabel('Name',{exact:true}).fill('Riverside Studio');await page.getByLabel('Email (optional)').fill('studio@example.test');await submit('Save contact');
await page.getByRole('button',{name:'+ Add contact'}).click();await page.getByLabel('Contact type').selectOption('supplier');await page.getByLabel('Name',{exact:true}).fill('Paper & Co.');await submit('Save contact');
await nav('Invoices');await page.getByRole('button',{name:'+ Create invoice',exact:true}).click();await page.getByLabel('Quantity',{exact:true}).fill('5');await page.getByLabel('Invoice tax rate').fill('7');await page.getByRole('button',{name:'+ Add product line'}).click();await page.getByLabel('Product',{exact:true}).nth(1).selectOption('2');await page.getByLabel('Quantity',{exact:true}).nth(1).fill('1');await submit('Issue invoice');await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Record payment',exact:true}).click();await page.getByLabel('Amount received',{exact:true}).fill('500');await submit('Record payment');
await nav('Purchase orders');await page.getByRole('button',{name:'+ Purchase order',exact:true}).click();await page.getByLabel('Product',{exact:true}).selectOption('2');await page.getByLabel('Quantity',{exact:true}).fill('10');await submit('Create order');await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Receive all stock'}).click();await submit('Confirm');
await nav('Expenses');await page.getByRole('button',{name:'+ Record expense',exact:true}).click();await page.getByLabel('Amount paid').fill('1200');await page.getByLabel('Payee',{exact:true}).fill('Paper & Co.');await page.getByLabel('Note / purchase order reference').fill('PO-00001');await submit('Record expense');
await nav('Overview');await page.screenshot({path:path.join(out,'overview-desktop.png'),fullPage:true});
await nav('Inventory');await page.getByLabel('Search records').fill('notebook');await page.getByText('1 records',{exact:true}).waitFor();await page.getByRole('button',{name:'Adjust',exact:true}).click();await page.getByLabel('Stock change').fill('-1');await page.getByLabel('Reason · for your stock history').fill('Damaged unit');await submit('Save adjustment');
await nav('Invoices');await page.getByRole('button',{name:'Open',exact:true}).click();await page.screenshot({path:path.join(out,'invoice-desktop.png')});await page.emulateMedia({media:'print'});await page.pdf({path:path.join(out,'invoice-test.pdf'),format:'A4'});await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'Close dialog'}).click();
await nav('Reports');const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'↓ Download CSV'}).first().click();const download=await downloadPromise;if(!download.suggestedFilename().endsWith('.csv'))throw new Error('CSV download failed');
await nav('Settings');await page.getByRole('button',{name:'+ Add team member',exact:true}).click();await page.getByLabel('Full name').fill('Demo Viewer');await page.getByLabel('Username',{exact:true}).fill('viewer');await page.getByLabel('Initial password').fill('viewer-password-123');await page.getByLabel('Role',{exact:true}).selectOption('viewer');await submit('Create account');
await page.setViewportSize({width:390,height:844});await nav('Overview');await page.screenshot({path:path.join(out,'overview-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);if(overflow)throw new Error('Mobile page overflow');
await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('viewer');await page.getByLabel('Password',{exact:true}).fill('viewer-password-123');await page.getByRole('button',{name:'Sign in →',exact:true}).click();await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();await nav('Inventory');if(await page.getByRole('button',{name:'+ Add product',exact:true}).count())throw new Error('Viewer has create control');
console.log(JSON.stringify({ok:true,errors,flows:['setup','settings','products','contacts','multi-line invoice','partial payment','purchase receiving','expense','search','stock adjustment','print','CSV download','team account','mobile layout','viewer controls']}));if(errors.length)process.exitCode=1;
}finally{await browser.close();await new Promise(r=>app.server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
})();
