'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
// Test HTML generation and escaping without pretending this is a browser-layout test.
const elements=new Map();
const element=()=>({innerHTML:'',className:'',textContent:'',open:false,addEventListener(){},querySelectorAll(){return [];},showModal(){this.open=true;},close(){this.open=false;}});
const document={documentElement:{lang:'en',dataset:{}},querySelectorAll(){return [];},querySelector(selector){if(!elements.has(selector))elements.set(selector,element());return elements.get(selector);},addEventListener(){}};
const context=vm.createContext({document,Intl,Date,console,setTimeout,clearTimeout,crypto:require('node:crypto').webcrypto});
const source=fs.readFileSync(path.resolve(__dirname,'../../public/app.js'),'utf8').replace(/boot\(\);\s*$/,'');
vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../public/i18n.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../public/health.js'),'utf8'),context);
vm.runInContext(source,context);
const run=code=>vm.runInContext(code,context);
const data={user:{id:1,name:'<img src=x onerror=alert(1)>',username:'owner',role:'admin'},settings:{name:'<script>attack()</script>',currency:'THB',address:'Bangkok',timezone:'Asia/Bangkok',version:1},products:[],contacts:[],invoices:[],payments:[],expenses:[],purchases:[],movements:[],users:[],audit:[],summary:{collected:0,outstanding:0,overdue:0,expenses:0,cashNet:0,lowStock:0,stockValue:0}};
run(`S=${JSON.stringify(data)};user=S.user;`);
test('all views generate for an empty business',()=>{for(const name of ['overview','health','inventory','invoices','purchases','contacts','expenses','reports','settings']){const html=run(`view='${name}';viewContent()`);assert.ok(html.length>100,name);assert.doesNotMatch(html,/\bNaN\b|\bundefined\b/,name);}});
test('stored HTML in business names is escaped',()=>{run('render()');const html=elements.get('#app').innerHTML;assert.ok(html.includes('&lt;script&gt;attack()&lt;/script&gt;'));assert.ok(html.includes('&lt;img src=x onerror=alert(1)&gt;'));assert.ok(!html.includes('<script>attack()'));});
test('viewer screen omits mutation and admin backup controls',()=>{run("user.role='viewer'");for(const name of ['overview','health','inventory','invoices','purchases','contacts','expenses','reports','settings']){const html=run(`view='${name}';headerActions()+viewContent()`);assert.doesNotMatch(html,/data-action="(?:product|invoice|purchase|expense|user|access|reset-password)"|href="\/api\/backup"/,name);}});
test('invoice status distinguishes overdue, partial, paid and void',()=>{assert.equal(run("status({status:'issued',due:'2000-01-01',total:100,paid:0})"),'overdue');assert.equal(run("status({status:'issued',due:'2999-01-01',total:100,paid:50})"),'partial');assert.equal(run("status({status:'issued',due:'2000-01-01',total:100,paid:100})"),'paid');assert.equal(run("status({status:'void',due:'2000-01-01',total:100,paid:0})"),'void');});
test('fresh browsers default to English even when storage is unavailable',()=>{const c=vm.createContext({document:{documentElement:{}},localStorage:{getItem(){throw new Error('blocked');},setItem(){throw new Error('blocked');}}});vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../public/i18n.js'),'utf8'),c);assert.equal(vm.runInContext('I18N.language',c),'en');assert.equal(vm.runInContext("I18N.t('Invoices')",c),'Invoices');});
test('saved Thai preference reloads and can return to English',()=>{const storage=new Map([['zetacaros.language','th']]);const c=vm.createContext({document:{documentElement:{}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)}});vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../public/i18n.js'),'utf8'),c);assert.equal(vm.runInContext("I18N.t('Invoices')",c),'ใบแจ้งหนี้');vm.runInContext("I18N.setLanguage('en')",c);assert.equal(storage.get('zetacaros.language'),'en');assert.equal(vm.runInContext("I18N.t('Invoices')",c),'Invoices');});
test('Thai rendering translates every main view and does not change record names',()=>{run("I18N.setLanguage('th');user.role='admin'");for(const name of ['overview','health','inventory','invoices','purchases','contacts','expenses','reports','settings']){run(`view='${name}';render()`);const html=elements.get('#app').innerHTML;assert.match(html,/ภาษา/);assert.match(html,/ขนาดตัวอักษร/);assert.doesNotMatch(html,/\$\{|undefined|NaN/);}const html=run("select('Customer','customer_id',[[1,'Customer'],[2,'<b>ลูกค้า</b>']],'',false)");assert.match(html,/>Customer<\/option>/);assert.match(html,/&lt;b&gt;ลูกค้า&lt;\/b&gt;/);run("I18N.setLanguage('en')");});
test('Thai server errors preserve product names and translate validation fields',()=>{run("I18N.setLanguage('th')");assert.match(run("I18N.error('Payment exceeds the remaining balance.')"),/มากกว่ายอดค้างชำระ/);assert.equal(run("I18N.error('Insufficient stock for Customer.')"),'สินค้า “Customer” มีจำนวนไม่พอ กรุณาลดจำนวนหรือรับสินค้าเพิ่ม');assert.match(run("I18N.error('Quantity must be a whole number from 1 to 100000.')"),/จำนวนต้องเป็นจำนวนเต็ม/);assert.equal(run("I18N.t('constructor')"),'constructor');run("I18N.setLanguage('en')");});
test('read-only dialogs suppress Enter submission and action buttons are non-submit',()=>{run("modal('Invoice details','<p>Read only</p>')");let prevented=false;elements.get('#modal-form').onsubmit({preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.match(run("btn('Open','view-invoice',1)"),/type="button"/);});
test('localized currency uses the same amount and dates remain canonical',()=>{run("I18N.setLanguage('th')");assert.match(run('money(12345)'),/123\.45/);assert.match(run('day()'),/^\d{4}-\d{2}-\d{2}$/);run("I18N.setLanguage('en')");assert.match(run('money(12345)'),/123\.45/);});
test('health charts preserve missing-month gaps and support negative cash values',()=>{
 const h=require('../src/health').businessHealth({today:'2026-09-13',invoices:[],products:[],payments:[{date:'2026-04-01',amount:1000},{date:'2026-06-01',amount:2000}],expenses:[{date:'2026-04-01',amount:2000,category:'Other',voided:0}]});
 run(`S.health=${JSON.stringify(h)};user.role='admin';I18N.setLanguage('en')`);const svg=run("healthGraph(S.health,'cash')");assert.match(svg,/<svg/);assert.doesNotMatch(svg,/NaN|Infinity/);const pathMatch=svg.match(/class="health-series" d="([^"]*)"/);assert.ok(pathMatch);assert.equal((pathMatch[1].match(/M/g)||[]).length,2);assert.equal((pathMatch[1].match(/L/g)||[]).length,0);
});
test('health page explains boundaries and renders Thai actions without leaking markup',()=>{
 run("I18N.setLanguage('th')");const html=run('health()');assert.match(html,/ควรทำอะไรต่อ/);assert.match(html,/ไม่ใช่กำไร/);assert.match(html,/ข้อมูลเดือนก่อนยังไม่พอ/);assert.doesNotMatch(html,/undefined|NaN|\$\{/);run("I18N.setLanguage('en')");
});
