'use strict';
// Optional real-browser regression suite. Install dev dependencies first (npm ci).
const {chromium}=require('playwright');
const {createApp}=require('../src/app');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const waitFor=async(page,fn)=>page.waitForFunction(fn,{},{timeout:10000});
(async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'zc-browser-'));
  const shots=process.env.ZC_SCREENSHOTS||dir;fs.mkdirSync(shots,{recursive:true});
  const app=createApp({dbPath:path.join(dir,'test.sqlite'),setupToken:'browser-test-code'});
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;
  let browser;const errors=[];let checks=0;
  const pass=label=>{checks++;console.log('PASS: '+label);};
  try{
    browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
    const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();
    page.on('pageerror',e=>errors.push(e.message));
    page.on('console',m=>{if(m.type()==='error'&&/Content Security Policy|Refused to/.test(m.text()))errors.push(m.text());});
    const api=async(url,data)=>page.evaluate(async({url,data})=>{const session=await(await fetch('/api/session')).json();const r=await fetch(url,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':session.user.csrf,'Idempotency-Key':crypto.randomUUID()},...(data===undefined?{}:{body:JSON.stringify(data)})});const body=await r.json();if(!r.ok)throw Error(JSON.stringify(body));return body;},{url,data});
    const nav=async id=>{await page.locator(`[data-page="${id}"]`).first().click();await waitFor(page,()=>!document.querySelector('dialog[open]'));await page.waitForTimeout(150);};
    await page.goto(base);await page.locator('#auth').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'en');
    for(const [name,value] of Object.entries({setupToken:'browser-test-code',name:'Maya',username:'owner',password:'browser-password-123'}))await page.locator(`[name="${name}"]`).fill(value);
    await page.locator('#auth button.primary').click();await page.locator('.stats').waitFor();assert.match(await page.locator('main').innerText(),/No sales recorded/);pass('English-first setup, empty real-data dashboard, no fake sales');
    await page.locator('[data-action="add-product"]').click();
    for(const [name,value] of Object.entries({name:'Jasmine tea',sku:'TEA-001',barcode:'8851234567898',price:'35.50',cost:'20',stock:'12',reorder:'3'}))await page.locator(`#product-form [name="${name}"]`).fill(value);
    await page.locator('#product-form button.primary').click();await page.locator('dialog').waitFor({state:'hidden'});
    let tea=(await api('/api/state')).products[0];assert.equal(tea.stock,12);pass('Add product through the UI, including barcode and decimal prices');
    await nav('products');await page.locator('[data-action="adjust"]').first().click();await page.locator('[name="quantity"]').fill('3');await page.locator('[name="reason"]').fill('Delivery arrived');await page.locator('#adjust-form button.primary').click();await page.locator('#confirm-form').waitFor();assert.equal((await api('/api/state')).products[0].stock,12);await page.locator('#confirm-form [data-action="close"]').click();assert.equal((await api('/api/state')).products[0].stock,12);pass('Review and Cancel do not change inventory');
    await page.locator('[data-action="adjust"]').first().click();await page.locator('[name="quantity"]').fill('3');await page.locator('[name="reason"]').fill('Delivery arrived');await page.locator('#adjust-form button.primary').click();await page.locator('#confirm-form button.primary').click();await page.locator('dialog').waitFor({state:'hidden'});assert.equal((await api('/api/state')).products[0].stock,15);pass('Confirm stock receipt updates quantity and history');
    await nav('scan');await page.locator('[data-action="sample"]').click();await page.locator('#scan-result .confirmation').waitFor();assert.match(await page.locator('#scan-result').innerText(),/Jasmine tea/);assert.equal((await api('/api/state')).products[0].stock,15);
    const decoded=await page.evaluate(async()=>{const element=document.querySelector('.barcode svg');element.setAttribute('xmlns','http://www.w3.org/2000/svg');const svg=element.outerHTML;return(await new ZXingBrowser.BrowserMultiFormatReader().decodeFromImageUrl('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg))).getText();});assert.equal(decoded,'8851234567898');pass('Sample EAN-13 actually decodes with ZXing; lookup does not alter stock');
    // Feed a real MediaStream from a canvas into the scanner to test the video decoding path.
    await page.evaluate(async()=>{const svg=document.querySelector('.barcode svg').outerHTML;const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await img.decode();const canvas=document.createElement('canvas');canvas.width=920;canvas.height=480;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,920,480);ctx.drawImage(img,0,70,920,340);window.testStream=canvas.captureStream(10);navigator.mediaDevices.getUserMedia=async()=>window.testStream;});
    await page.locator('[data-action="start-camera"]').click();await waitFor(page,()=>window.testStream.getTracks().every(t=>t.readyState==='ended'));assert.match(await page.locator('#scan-result').innerText(),/Jasmine tea/);pass('Video-stream barcode decode finds product and stops all camera tracks');
    await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await page.locator('[data-action="start-camera"]').click();await page.locator('#camera-message').filter({hasText:'Could not open camera'}).waitFor();await page.locator('#barcode-input').fill('NOT-FOUND');await page.locator('#barcode-form button').click();await page.locator('#scan-result').filter({hasText:'No matching product'}).waitFor();pass('Camera-denied fallback and unknown manual barcode handled');
    await page.locator('#barcode-input').fill('TEA-001');await page.locator('#barcode-form button').click();await page.locator('#scan-result [data-action="new-sale"]').click();await page.locator('[name="quantity"]').fill('2');await page.locator('#sale-form button.primary').click();await page.locator('#confirm-form').waitFor();assert.equal((await api('/api/state')).products[0].stock,15);assert.match(await page.locator('#confirm-form').innerText(),/71\.00/);await page.locator('#confirm-form button.primary').click();await page.locator('dialog').waitFor({state:'hidden'});assert.equal((await api('/api/state')).products[0].stock,13);pass('Sale from barcode search confirms total before deducting stock');
    await nav('products');await page.locator('[data-action="import"]').click();
    await page.locator('#csv-file').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('sku,name,price,cost,stock,reorder\nTEA-001,Existing,1,0,1,0\nBAD,Wrong,-1,0,2,0')});await page.locator('.row-error').first().waitFor();assert.equal(await page.locator('[data-action="commit-import"]').isDisabled(),true);assert.equal((await api('/api/state')).products.length,1);pass('Invalid CSV displays row errors and disables commit');
    const valid='\uFEFFsku,name,price,cost,stock,reorder,barcode\nMILK,Oat milk,65,35,3,5,001234\nCOFFEE,House blend coffee,180,95,20,5,\nHONEY,Wildflower honey,120,60,0,3,\nBREAD,Sourdough bread,85,40,2,4,\nWATER,Mineral water,15,8,48,12,';
    await page.locator('#csv-file').setInputFiles({name:'good.csv',mimeType:'text/csv',buffer:Buffer.from(valid)});await page.locator('.preview-stats .badge.good').waitFor();assert.equal((await api('/api/state')).products.length,1);await page.locator('[data-action="commit-import"]').click();await page.locator('#product-table').waitFor();assert.equal((await api('/api/state')).products.length,6);pass('Valid CSV previews all values and imports only after confirmation');
    await page.locator('#search').fill('001234');assert.match(await page.locator('#product-table').innerText(),/Oat milk/);assert.doesNotMatch(await page.locator('#product-table').innerText(),/Jasmine tea/);await page.locator('#search').fill('');
    assert.equal(await page.locator('.badge.low').count(),2);assert.equal(await page.locator('.badge.out').count(),1);pass('Barcode search, yellow low-stock and red out-of-stock text statuses');
    tea=(await api('/api/state')).products.find(p=>p.sku==='TEA-001');const o=await api('/api/overview');await api('/api/sales',{product_id:tea.id,quantity:3,version:tea.version,date:new Date(Date.parse(o.businessDay+'T12:00:00Z')-8*86400000).toISOString().slice(0,10)});
    await nav('sales');assert.match(await page.locator('.trend').innerText(),/Down -33\.3%/);await page.locator('#period').selectOption('30');await page.locator('.trend').filter({hasText:'New sales'}).waitFor();pass('Real-dated sales produce decline and 30-day comparison without invented percentages');
    await nav('dashboard');await page.locator('#quick-search input').fill('001234');await page.locator('#quick-search button').click();await page.locator('#product-table').waitFor();assert.match(await page.locator('#product-table').innerText(),/Oat milk/);assert.doesNotMatch(await page.locator('#product-table').innerText(),/Jasmine tea/);pass('Dashboard quick search opens the matching inventory');
    await nav('dashboard');await page.locator('[data-action="stock-filter"][data-filter="out"]').click();await page.locator('#product-table').waitFor();assert.match(await page.locator('#product-table').innerText(),/Wildflower honey/);assert.doesNotMatch(await page.locator('#product-table').innerText(),/Oat milk/);pass('Clickable stock summary opens the correct filtered products');
    await nav('dashboard');const stockBefore=(await api('/api/state')).products;await page.locator('[data-action="receive-stock"]').click();await page.locator('#receive-picker select').selectOption(String(tea.id));await page.locator('#receive-picker button.primary').click();await page.locator('#adjust-form').waitFor();assert.equal(await page.locator('#adjust-form [name="direction"]').inputValue(),'in');await page.locator('#adjust-form [data-action="close"]').click();assert.deepEqual((await api('/api/state')).products,stockBefore);await page.locator('.attention-panel [data-action="adjust"]').first().click();await page.locator('#adjust-form').waitFor();await page.locator('#adjust-form [data-action="close"]').click();pass('Receive-stock picker and alert shortcuts preserve confirmation and cancellation');
    await page.locator('#toast').waitFor({state:'hidden'});await page.screenshot({path:path.join(shots,'dashboard-desktop.png'),fullPage:true});
    for(const language of ['th','en']){await page.locator('[data-action="language"]').click();assert.equal(await page.locator('html').getAttribute('lang'),language);for(const id of ['products','sales','history','settings','scan','dashboard']){await nav(id);assert.doesNotMatch(await page.locator('main').innerText(),/undefined|NaN|\$\{/);}pass('All six main screens render in '+language);}
    for(const width of [390,768]){await page.setViewportSize({width,height:844});for(const id of ['dashboard','products','scan','sales','history','settings']){await nav(id);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal page overflow: '+width+' '+id);}pass('Responsive layouts have no page overflow at '+width+'px');}
    await page.setViewportSize({width:390,height:844});await page.locator('[data-action="language"]').click();await nav('dashboard');await page.screenshot({path:path.join(shots,'dashboard-mobile-th.png'),fullPage:true});await nav('products');await page.screenshot({path:path.join(shots,'products-mobile-th.png'),fullPage:true});
    const download=page.waitForEvent('download');await page.locator('a[href="/api/inventory.csv"]').click();const downloaded=await download;await downloaded.saveAs(path.join(dir,'inventory.csv'));assert.match(fs.readFileSync(path.join(dir,'inventory.csv'),'utf8'),/001234/);pass('CSV export downloads and keeps barcode zeros');
    await nav('settings');const backupEvent=page.waitForEvent('download');await page.locator('a[href="/api/backup"]').click();const backup=await backupEvent;await backup.saveAs(path.join(dir,'downloaded.sqlite'));require('../src/maintenance').check(path.join(dir,'downloaded.sqlite'));pass('Backup UI downloads a valid database');
    await page.reload();await page.locator('.topbar').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'th');await page.locator('[data-action="logout"]').click();await page.locator('#auth').waitFor();await page.locator('[name="username"]').fill('owner');await page.locator('[name="password"]').fill('wrong');await page.locator('#auth button.primary').click();await page.locator('#auth .error').filter({hasText:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'}).waitFor();pass('Language persists after reload; logout and translated login errors work');
    assert.deepEqual(errors,[]);pass('No browser JavaScript or Content Security Policy errors');
    console.log(`PASS: ${checks} browser checks. Screenshots: ${shots}`);
  }finally{await browser?.close();await new Promise(r=>app.server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
